---
- name: Capturing Existing Configurations
  ansible.builtin.find:
    paths: /etc/netplan
    patterns: "*.yml,*.yaml"
  register: _netplan_configs

- name: Debugging Existing Configurations
  ansible.builtin.debug:
    var: _netplan_configs
  when: debug is defined and ( debug | bool )

- name: Removing Existing Configurations
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ _netplan_configs['files'] }}"
  when:
    - item['path'] != netplan_config_file
    - netplan_configuration != []
