---
- name: Install netplan
  ansible.builtin.import_tasks: install.yml

- name: Remove existing netplan configuration
  ansible.builtin.import_tasks: existing.yml
  when:
    - netplan_remove_existing

- name: Configure netplan
  ansible.builtin.import_tasks: configure.yml
  when:
    - netplan_configuration is defined
    - netplan_configuration != {}
