---
- name: Generating Netplan Configuration
  ansible.builtin.command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
  changed_when: false

- name: Applying Netplan Configuration
  ansible.builtin.command: netplan apply
  listen: netplan apply config
  changed_when: false
